/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c WMSwitcher -p generated/com_deepin_wmswitcher ../xml/com.deepin.WMSwitcher.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef COM_DEEPIN_WMSWITCHER_H
#define COM_DEEPIN_WMSWITCHER_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <DBusExtendedAbstractInterface>
#include <QtDBus/QtDBus>


/*
 * Proxy class for interface com.deepin.WMSwitcher
 */
class __WMSwitcherPrivate;
class __WMSwitcher : public DBusExtendedAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticInterfaceName()
    { return "com.deepin.WMSwitcher"; }

public:
    explicit __WMSwitcher(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~__WMSwitcher();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<bool> AllowSwitch()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("AllowSwitch"), argumentList);
    }



    inline QDBusPendingReply<QString> CurrentWM()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("CurrentWM"), argumentList);
    }



    inline QDBusPendingReply<> RequestSwitchWM()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RequestSwitchWM"), argumentList);
    }

    inline void RequestSwitchWMQueued()
    {
        QList<QVariant> argumentList;

        CallQueued(QStringLiteral("RequestSwitchWM"), argumentList);
    }


    inline QDBusPendingReply<> RestartWM()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("RestartWM"), argumentList);
    }

    inline void RestartWMQueued()
    {
        QList<QVariant> argumentList;

        CallQueued(QStringLiteral("RestartWM"), argumentList);
    }


    inline QDBusPendingReply<> Start2DWM()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QStringLiteral("Start2DWM"), argumentList);
    }

    inline void Start2DWMQueued()
    {
        QList<QVariant> argumentList;

        CallQueued(QStringLiteral("Start2DWM"), argumentList);
    }



Q_SIGNALS: // SIGNALS
    void WMChanged(const QString &in0);
    // begin property changed signals

public Q_SLOTS:
    void CallQueued(const QString &callName, const QList<QVariant> &args);

private Q_SLOTS:
    void onPendingCallFinished(QDBusPendingCallWatcher *w);

private:
    __WMSwitcherPrivate *d_ptr;
};

namespace com {
  namespace deepin {
    typedef ::__WMSwitcher WMSwitcher;
  }
}
#endif
