version = 1
SPDX-PackageName = "dde-application-manager"
SPDX-PackageSupplier = "UnionTech Software Technology Co., Ltd. <>"
SPDX-PackageDownloadLocation = "https://github.com/linuxdeepin/dde-application-manager"

[[annotations]]
path = ["README.md", "README.zh_CN.md", "docs/**", "examples/launchApp/README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "**CMakeLists.txt"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [".github/**", ".gitlab-ci.yml", ".obs/workflows.yml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "api/**.cmake.in"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["api/dbus/**.xml", "apps/app-update-notifier/api/dbus/**.xml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["rpm/**", "debian/**", "archlinux/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tests/data/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["misc/dpkg/dpkg.cfg.d/**", "misc/hooks.d/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "misc/dsg/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "toolGenerate/**/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".clang-format"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 - 2026 UnionTech Software Technology Co., Ltd."
SPDX-License-Identifier = "CC0-1.0"
